plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: true
  Max: 40
  Exclude:
    - "spec/**/*_spec.rb"
    - "config/routes.rb"
    - "config/environments/*.rb"

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument
  Exclude:
    - "spec/**/*_spec.rb"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 40

Rails/TransactionExitStatement:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/InstanceVariable:
  Enabled: true
  Exclude:
    - "spec/controllers/**/*_spec.rb"

RSpecRails/InferredSpecType:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Exclude:
    - "db/migrate/**/*.rb"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/**/*.rb"

Style/SymbolArray:
  Exclude:
    - "db/migrate/**/*.rb"

Rails/TimeZone:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

Style/Documentation:
  Enabled: false # どこでもドキュメントを強制しない

Metrics/CyclomaticComplexity:
  Max: 12 # 複雑度のしきい値を引き上げ

Metrics/PerceivedComplexity:
  Max: 12 # 認知複雑度のしきい値を引き上げ

Metrics/AbcSize:
  Max: 55 # メソッド内の処理量の制限を緩和

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb' # 長いURLが含まれるファイルを対象外に

RSpec/AnyInstance:
  Enabled: false # テストでの allow_any_instance_of を許容する（修正が大変なため）