FROM ruby:3.3.6

RUN apt-get update -qq \
 && apt-get install -y nodejs postgresql-client npm vim \
 && rm -rf /var/lib/apt/lists/* \
 && npm install --global yarn

RUN gem uninstall bundler -a -x \
    && gem install bundler -v 2.6.3

ENV BUNDLE_PATH=/myapp/vendor/bundle
ENV GEM_HOME=/usr/local/bundle
ENV PATH /myapp/bin:$GEM_HOME/bin:$PATH

RUN mkdir /myapp
WORKDIR /myapp

RUN bundle config set path '/myapp/vendor/bundle'

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

COPY package.json yarn.lock /myapp/

RUN bundle _2.6.3_ install

RUN yarn install

ADD . /myapp

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
